### ISSUE TITLE
pressure sense feature not working

### ISSUE THREAD

**Issue by yotamguttman** [icedman/dash2dock-lite#116]
I absolutely love this extension but I haven't been able to use it because the autohide (force visibility) function tends to act up. I had to go for the standard and boring 'dash to dock' instead where the autohide is quite a bit more reliable.

this recording shows **dash2dock animated** auto hide, when a window is overlapping it. my pointer only occasionally triggers the raise of the dock, in this video, it did not trigger it at all:
https://github.com/icedman/dash2dock-lite/assets/92977002/a855ef25-f80b-4cb3-8bde-a9c213af37ca

additionally, it often interferes with the UI in fullscreen when software is maximised.
for example, when I use Inkspace in fullscreen and try accessing parameters at the bottom of the screen (like the colour palette bar), dash2dock animated obstructs the access to the software's UI underneath, even when hidden. if you've used 'dash to dock', this never happens. it comes up every time and only when you need it to.

---

this recording shows how smooth this works with 'dash to dock'
https://github.com/icedman/dash2dock-lite/assets/92977002/29c68851-520f-4864-b9c3-492cef0e0f18

I really hope this can be sorted out eventually. I absolutely love this extension! it looks very neat, the animations are pristine and the experience is unique and beautiful! thank you for making it :)

**Comment by yotamguttman** [comment]
p.s.

my other extensions, in case you've identified compatibility issues:

- add-to-desktop@tommimon.github.com
- blur-my-shell@aunetx
- clipboard-indicator@tudmotu.com
- dash2dock-lite@icedman.github.com
- dash-to-dock@micxgx.gmail.com
- gtk4-ding@smedius.gitlab.com
- panel-corners@aunetx
- quick-settings-tweaks@qwreey
- soft-brightness-plus@joelkitching.com
- tiling-assistant@leleat-on-github
- weatheroclock@CleoMenezesJr.github.io
- wiggle@mechtifs

**Comment by icedman** [comment]
Thank you for the detailed explanations. Please indicate your Gnome version and OS Flavor. Thanks.

**Comment by yotamguttman** [comment]
sure. 
Fedora 39 running Gnome 45.5 (had this problem on Gnome 45 as well).

cheers!

**Comment by icedman** [comment]
I tested on Fedora 39, Gnome 45.0; The pressure sense works for me. But I had to set sensitivity to full 100%. Could you try playing around the settings (Tweaks tab; Pressure-sense-itivity).

Also try disabling pressure sense, to isolate the problem.

To be clear: The behavior for pressure sense is that you have to move the mouse at the very bottom of the screen. And you have to move it some more at roughly the same area. (As if to push and give pressure). Less sensitivity means you have to push a lot more. Most sensitivity  means you only give a tiny nudge for the dock to popup.

**Comment by MarsSwimmer** [comment]
the same problem, I found it show on x11 desktop environment, my os info:

- ubuntu 23.10
- Gnome version 45.2

my other extension:
- blur-my-shell@aunetx
- justperfection

especially, if click icon from dock doesnt open app window, or doesnt show download folder expand animator, it will block dock, sometime block screen, cant do anything, its only show on x11 desktop environment.

**Comment by icedman** [comment]
I pushed a fix for X11. Where you cannot click the dock. Thanks for catching this nasty bug.

**Comment by yotamguttman** [comment]
I might've got you wrong but why X11? I run Wayland and the issue is still present. still unable to pull the dock by dragging my cursor down, if an app is in fullscreen or placed underneath it. it disappears and would only reappear once I reposition the app.

**Comment by millsp** [comment]
For me this was happening because the "edge distance" setting was too high, out off the screen I guess.
@icedman my dock is not transparent so that means for it to work it has to float over all my apps.
That is fine most of the time except for movies. Maybe you could consider adding a transparent edge?

**Comment by yotamguttman** [comment]
I'm still facing the same issues to be honest. I had to revert to the old dash to dock extension unfortunately. I love @icedman's version so much more but I kept running into more and more bugs with this one.

it still doesn't rise for me on auto hide when an app is in full screen and as I mentioned before, when it's tucked down, there's a whole area at the bottom across my whole display (side to side), where the dock would've been, that is not accessible so I cannot interact with any UI elements at the bottom of a window if maximised...

also sometimes the original Gnome dock randomly comes back in overview and then I get the 2 docks overlapping...
