### ISSUE TITLE
The Dock is Showing when I full screen any of my window 

### ISSUE THREAD

**Issue by mohammed-tahmid-sudo** [icedman/dash2dock-lite#160]
Hey There!, I have been using you Extensions for too long time. And I really love it but the only problem that I have when I full screen any of my windows like YouTube videos it's still showing. And its annoying I have been trying to use another Extension or application but those are not as good and customizable as your extension

**Comment by icedman** [comment]
Fixed with latest update. Please verify on your side. Thanks!

**Comment by phantom-8** [comment]
I'm having the same problem.  That is, the dock still shows when I'm running full screen app, like youtube.  FYI, I'm using the latest version 71 downloaded from Gnome Extensions repsosity.
