### ISSUE TITLE
Scroll on minimized app icon should bring it up

### ISSUE THREAD

**Issue by TheWeirdDev** [icedman/dash2dock-lite#71]
Currently when you scroll on an app icon that's minimized, nothing happens (It's very confusing). But user expects it to show up.

Showing the window is also how Dash to dock works, so it would be nice if the two extensions behaved similarly.

**Comment by icedman** [comment]
dash2dock lite actually has some more controls on the icons than dash to dock. you just need to get used to them.
minimize/restore > click
maximize/restore > shift+click
open new window > control+click
scroll-up down > cycle windows (if more than one window is open)

**Comment by TheWeirdDev** [comment]
I know but when the window is minimized it does not un-minimize on scroll. By looking at the code I see you [call unminimize](https://github.com/icedman/dash2dock-lite/blob/57518874a174b29f8ee597bec47171c2173c32a8/animator.js#L1068) but I do not see any effect. The window stays minimized.

Maybe you should call [Main.activateWindow()](https://github.com/micheleg/dash-to-dock/blob/26338514e13a142914c6f94295c0ea70b411d4a7/appIcons.js#L562C48-L562C48)?

**Comment by icedman** [comment]
Ok. Will check these bugs.

**Comment by icedman** [comment]
Fixed on the development branch. I also uploaded to EGO, awaiting review.

**Comment by TheWeirdDev** [comment]
Thanks. I tried it and it works much better now. There is only one issue. When there is only one window of an application, un-minimize still does not work but when I have multiple windows it works.
